apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: k37kfqty2-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:efba91c1bcdd82ca54534c3ec5cfe6a4cd8988ed@sha256:87005fb92b9e2d3859e6cd3240f739f553db08983cc7e2282ad2682e46e32053
          name: container-image
